### ISSUE TITLE
上拉加载 如果tableView无内容,上拉加载还是会触发并绘制footView

### ISSUE THREAD

**Issue by zhangjunjiecq** [liutongchao/LCRefresh#4]

**Comment by zhangjunjiecq** [comment]
重新绘制refreshFootView  因为contentSize.height是0 所以视图会再最上面

**Comment by zhangjunjiecq** [comment]
发起了一个pull request 你看下是否可以解决

**Comment by liutongchao** [comment]
谢谢提出问题，可以解决，但是如果数据没铺满一页上拉刷新就不会触发，想了想对于上拉刷新来讲，影响应该不大。

**Comment by zhangjunjiecq** [comment]
如果页面是空时 或数据源是空时 上拉加载会触发 并且会展示上拉加载更多
